// Code generated by ogen, DO NOT EDIT.

package ogen_log_gen

import (
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

type Entry jx.Raw

// Encode encodes Entry as json.
func (s Entry) Encode(e *jx.Encoder) {
	unwrapped := jx.Raw(s)
	if len(unwrapped) != 0 {
		e.Raw(unwrapped)
	}
}

// Decode decodes Entry from json.
func (s *Entry) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode Entry to nil")
	}
	var unwrapped jx.Raw
	if err := func() error {
		v, err := d.RawAppend(nil)
		unwrapped = jx.Raw(v)
		if err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "alias")
	}
	*s = Entry(unwrapped)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s Entry) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Entry) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
